spring:
  # dotenv
  config:
    import: optional:file:.env[.properties]
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com
  data:
    mongodb:
      database: ${MONGO_DATABASE}
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}
